KillMessages:
    default:
        label: "&aDefault"
        message: "&f%killer% &7killed &f%victim%. %killstreak%"
        order: 1
    smacked:
        label: "&2Smacked"
        message: "&f%killer% &a&osmacked &f%victim%. %killstreak%"
        order: 2
    rekt:
        label: "&4Rekt"
        message: "&f%killer% &c&orekt &f%victim%. %killstreak%"
        order: 3
KillStreaks:
    5:
      kills: 5
      message: "&f%player% &anow has a 5 kill streak!"
      commands:
        - eco give %player% 5
    10:
      kills: 10
      message: "&f%player% &2now has a 10 kill streak!"
      commands:
        - eco give %player% 10
    15:
      kills: 15
      message: "&f%player% &cnow has a 15 kill streak!"
      commands:
        - eco give %player% 15